# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E9BLCpDmtXRlRJaousIdiltIrLtBjg9-

**Bubble sort**
"""

from array import*

def bubble_sort(arr,n):
  for i in range(n):
    for j in range(n-i-1):
      if(arr[j]>arr[j+1]):
        temp = arr[j]
        arr[j] , arr[j+1] = arr[j+1] , temp


def main():
  arr = array('i',[])
  print("Enter the size of the array :: ")
  n = int(input())

  for i in range(n):
    print("Enter the value of the array :: ")
    arr.append(int(input()))

  print("Original array is :: ",arr)

  bubble_sort(arr,n)

  print("Sorted array is :: ",arr)

if __name__ == "__main__":
  main()

**    Linear Search **

    
from array import*

def linear_search(arr,ele,n):
  for i in range(n):
    if(arr[i] == ele):
      return i
  return -1


def main():
  arr = array('i',[])
  print("Enter the size of the array :: ")
  n = int(input())

  for i in range(n):
    print("Enter the value of the array :: ")
    arr.append(int(input()))

  print("Original array is :: ",arr)

  print("Enter the search element :: ")
  element = int(input())

  result = linear_search(arr,element,n)

  if result!=-1:
    print("Search Successful!!The element ",element," is found ata the position ",(result+1))
  else:
    print("Search Unsucessful!!Not found")

if __name__ == "__main__":
  main()
